### ISSUE TITLE
Docker版中无法配置开启ip转发

### ISSUE THREAD

**Issue by xietao1233** [mzz2017/V2RayA#66]
### Version, approach of installation, operating system
在群辉nas中部署docker, 开启ip转发后出现以下错误:
2020/04/03 14:05:14 [Warning] V2RayA/core/ipforward: sh: can't create /proc/sys/net/ipv4/ip_forward: Read-only file system

建议增加docker配置, 允许docker启动的时候立即开启ip转发.
另外获得GFWList 也失败了
[Warning] V2RayA/core/gfwlist: fail in get latest version of GFWList > Get "https://api.github.com/repos/mzz2017/d...

1. What version of V2RayA are you using?

2. What approach of installation do you install V2rayA?

3. What is your operating system and CPU architecture?

### Logs：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 100
 
 # docker mode
 docker logs v2raya_backend
 ```
```shell
# Paste running logs here



```

**Comment by xietao1233** [comment]
What version of V2RayA are you using?
V2Ray v4.23.1 (v2fly/ea62c931) dockerfly-amd64 (go1.14.1 linux/amd64)

What approach of installation do you install V2rayA?

What is your operating system and CPU architecture?
群晖 nas ds718+ x64

**Comment by xietao1233** [comment]
> 请开启privileged和network host即可解决 mzz2017 m@mzz.pub
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: xietao1233 <notifications@github.com&gt; 发送时间: 2020年4月3日 23:58 收件人: mzz2017/V2RayA <V2RayA@noreply.github.com&gt; 抄送: Subscribed <subscribed@noreply.github.com&gt; 主题: 回复：[mzz2017/V2RayA] Docker版中无法配置开启ip转发 (#66) What version of V2RayA are you using? V2Ray v4.23.1 (v2fly/ea62c931) dockerfly-amd64 (go1.14.1 linux/amd64) What approach of installation do you install V2rayA? What is your operating system and CPU architecture? 群晖 nas ds718+ x64 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

群晖nas上的docker比较特殊, 无法通过docker命令启动, 直接导入这个项目又会报:
Import container from [Dockerfile] failed: [Invalid file format]

**Comment by mzz2017** [comment]
这两个都有对应的选项，仔细找找




mzz2017
m@mzz.pub




------------------ 原始邮件 ------------------
发件人: xietao1233 <notifications@github.com&gt;
发送时间: 2020年4月4日 09:42
收件人: mzz2017/V2RayA <V2RayA@noreply.github.com&gt;
抄送: mzz <m@mzz.pub&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[mzz2017/V2RayA] Docker版中无法配置开启ip转发 (#66)





  
请开启privileged和network host即可解决 mzz2017 m@mzz.pub
 …
 ------------------ 原始邮件 ------------------ 发件人: xietao1233 <notifications@github.com&gt; 发送时间: 2020年4月3日 23:58 收件人: mzz2017/V2RayA <V2RayA@noreply.github.com&gt; 抄送: Subscribed <subscribed@noreply.github.com&gt; 主题: 回复：[mzz2017/V2RayA] Docker版中无法配置开启ip转发 (#66) What version of V2RayA are you using? V2Ray v4.23.1 (v2fly/ea62c931) dockerfly-amd64 (go1.14.1 linux/amd64) What approach of installation do you install V2rayA? What is your operating system and CPU architecture? 群晖 nas ds718+ x64 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
群晖nas上的docker比较特殊, 无法通过docker命令启动, 直接导入这个项目又会报:
 Import container from [Dockerfile] failed: [Invalid file format]

**Comment by xietao1233** [comment]
> 这两个都有对应的选项，仔细找找 mzz2017 m@mzz.pub
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: xietao1233 <notifications@github.com&gt; 发送时间: 2020年4月4日 09:42 收件人: mzz2017/V2RayA <V2RayA@noreply.github.com&gt; 抄送: mzz <m@mzz.pub&gt;, Comment <comment@noreply.github.com&gt; 主题: 回复：[mzz2017/V2RayA] Docker版中无法配置开启ip转发 (#66) 请开启privileged和network host即可解决 mzz2017 m@mzz.pub … ------------------ 原始邮件 ------------------ 发件人: xietao1233 <notifications@github.com&gt; 发送时间: 2020年4月3日 23:58 收件人: mzz2017/V2RayA <V2RayA@noreply.github.com&gt; 抄送: Subscribed <subscribed@noreply.github.com&gt; 主题: 回复：[mzz2017/V2RayA] Docker版中无法配置开启ip转发 (#66) What version of V2RayA are you using? V2Ray v4.23.1 (v2fly/ea62c931) dockerfly-amd64 (go1.14.1 linux/amd64) What approach of installation do you install V2rayA? What is your operating system and CPU architecture? 群晖 nas ds718+ x64 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 群晖nas上的docker比较特殊, 无法通过docker命令启动, 直接导入这个项目又会报: Import container from [Dockerfile] failed: [Invalid file format] — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

      "docker模式下如果未使用<code>--privileged --network host</code>参数启动容器，可通过修改端口映射修改socks5、http端口。",
      "docker模式下不能正确判断端口占用，请确保输入的端口未被其他程序占用。",
映射一下docker端口就解决了, 谢了
你说的是这一句吧, 我还是在源码中看到的, gui里并没有显示这句话, 貌似并没有正确的识别到当前运行环境是docker.

**Comment by mzz2017** [comment]
对的，没有判断参数是否正确，所以建议按照wiki进行配置。
